version: "3"

services:
  story-api:
    container_name: story-api
    image: story-api
    ports:
    - 4396:4396
    depends_on:
    - mongo2
    links:
    - mongo2
  mongo2:
    container_name: mongo2
    image: mongo
    ports:
    - 27030:27017
